### ISSUE TITLE
Lastname, Firstname

### ISSUE THREAD

**Issue by joshuacwnewton** [joshuacwnewton/test-github-action-wiki#23]
```{note}
Fill out this membership card to record what access each lab member has or should have.
 
Make sure to leave comments for future reference to record any roadblocks,
solutions or changes to their role made during their time at the lab!
```

### 1.0 Commencement

- [x] [Create a new issue](https://github.com/neuropoly/onboarding/issues/new/choose) using this "Onboarding" template.
- [ ] Replace the title **"Lastname, Firstname"** with their name.
- [ ] Pick someone from the admin team to be the **Onboarding Lead** (it could be yourself!). Assign this issue to them.
- [ ] Hit "Submit new issue".

### 1.1 Tasks for @jcohenadad

- Check off role and complete tasks accordingly; **either**:

  - [ ] _Faculty_
    - <details>
      <summary> Tasks </summary>
      
      TODO

      </details>
  - [ ] {_Postdoctoral Researcher_,{_PhD_,_MSc_} _Student_,_Internship_}:
    - <details>
      <summary> Tasks </summary>
      
      - [ ] Update the [`students_julien`](https://docs.google.com/spreadsheets/d/152_06eZBIqZNTd4uw2ZIV7tVbVCTkDWvxBw5ZqT5nfU/edit#gid=34359562) supervision spreadsheet.
      - [ ] Regarding contract / aide financière, contact **either**:
        - {_Postdoctoral Researcher_,{_PhD_,_MSc_} _Student_}: dge.sec-biomedical@polymtl.ca
        - _Internship_: dge.stagiaires@polymtl.ca

      </details>       
  - [ ] _Research associate_
    - <details>
      <summary> Tasks </summary>
      
      - [ ] Send an email to the new member detailing a list of their employee tasks/responsibilities.
      - [ ] Ask the member to provide CV, 1st university cycle diploma (e.g. copy of Bachelor degree), and a completed copy of [`FichePersonnelleNouvelEmploye.docx`](https://github.com/neuropoly/onboarding/raw/main/FichePersonnelleNouvelEmploye.docx), then send these documents to dge.sec-biomedical@polymtl.ca.
      
      </details>
  - [ ] _Consultant_
    - <details>
      <summary> Tasks </summary>
      
      - [ ] Offer [this invoice template](https://www.dropbox.com/s/ix24bmaekk97hsy/invoice_consulting_template.docx?dl=1).
         - This isn't mandatory! A consultant can use their own for payment instead. This is just for people who do not have a pre-existing consultancy.
         - Invoices should be submitted by the consultant every 2 weeks to jcohen@polymtl.ca, who will forward it to TODO@polymtl.ca.
      - [ ] For Canadian citizens, especially if their consultancy is indeterminate, inform them about the 30 000$ threshold for small business tax collection (HST/QST), both [federal](https://www.canada.ca/en/revenue-agency/services/tax/businesses/topics/gst-hst-businesses/when-register-charge.html) (HST/TPS) and [provincial](https://www.revenuquebec.ca/fr/entreprises/taxes/tpstvh-et-tvq/inscription-aux-fichiers-de-la-tps-et-de-la-tvq/petit-fournisseur/) (TVQ).
     
          ```{warning}
           Other countries have their own tax laws. We do not have exhaustive experience
           with any particular citizenship interacts with Quebec's financial laws.
           ```
      </details>
      
- Check off which projects the member will be focusing on. (This will determine which GitHub orgs, Slack channels, Google groups, etc., they are given access to.)
    - [ ] AxonDeepSeg
    - [ ] Ivadomed
    - [ ] qMRLab
    - [ ] Shimming Toolbox
    - [ ] SpinalCordToolbox / SCT Pipeline
    - [ ] Spine Generic

  
### 1.2 Accounts

- [x] PolyMtl (`{u,p}######`, `firstname.lastname@polymtl.ca`, `user@grames.polymtl.ca`)
  <details>
  <summary> Tasks </summary>
  
  - **If** {_Research associate_,_Consultant_}
    - [ ] Send email to dge.acces@polymtl.ca to ask for [CAS](https://cas5.polymtl.ca/cas/) account (for VPN, `@polymtl.ca` email, `eduroam`, and [WebEx](https://teams.webex.com)).
    - [ ] Verify they can manage this account from https://codes.si.polymtl.ca/. (Make sure they know that this portal is only available on campus or via the VPN.)
  - [ ] Have them out this [form](https://www.grames.polymtl.ca/facilities/servers-information/create_account/) for a [PolyGRAMES](https://www.grames.polymtl.ca/) account.
  - [ ] Write their matricule, email address, GRAMES username in the section title.
    </details>
- [ ] Physical building access
  <details>
  <summary> Tasks </summary>
    
  - [ ] If they're remote (i.e. not in Montreal), then skip the tasks and just check this box. Otherwise:
  - [ ] Get them a personnel/étudiant/invité [ID card](https://www.polymtl.ca/surete/services#carte-didentite):
    - **If** {_Research associate_,_Consultant_}:
      - [ ] Have them fill out [this form](https://share.polymtl.ca/alfresco/service/api/path/content;cm:content/workspace/SpacesStore/Company%20Home/Sites/surete-web/documentLibrary/formulaires/Demande_carte_identite.pdf?a=true&guest=true) and send it to you. (Under "_Accès au lecteur # du local_" write "L5613, L5626".)
      - [ ] Forward it to dge.acces@polymtl.ca, CC'ing the new member.
      - [ ] dge.acces@polymtl.ca will sign it and return it, possibly by email, possibly by paper at their office.
      - [ ] Have the new member [book an appointment with sûreté](https://book.timify.com/?accountId=5f33b2e6dcd62212cf907c23&hideCloseButton=true) to have a photo taken and ID card issued. Make sure they remember to bring an existing photo ID [acceptable to sûreté](https://www.polymtl.ca/surete/services#carte-didentite).
    - **If** _Student_:
      - [ ] Take their [existing student ID card](https://www.polymtl.ca/surete/services#pour-les-etudiants) and request room access to L5613 and L5626 by emailing sur-acces@polymtl.ca (and CC'ing the new member) with [the details listed here](https://www.polymtl.ca/surete/services#acces-un-local-ou-une-salle). (For the expiry date, choose it to match the expected end of the degree or internship, or if not known, match it to the expiry date on the card.)
    - [ ] Verify card grants access to L5613 and L5626.
      - If not, talk to sûreté in person at the [entrance to the pavillion prinicipal](https://www.polymtl.ca/surete/coordonnees-et-bottin/coordonnees), A-100. (They may send you back to dge.access@polymtl.ca or sur-access@polymtl.ca; or, they may call and directly ask for confirmation while you wait.)
    - [ ] Assign a desk in **either** L5613 (RF/hardware-focused) or L5626 (software-focused) by editing their name into an open slot on [this table](https://docs.google.com/document/d/11GEh5YvYRnWnERv26TezcyvyPF2W5KF0uoI2U6p7XsM/edit).
  </details>
